"""schema v5

Revision ID: a857605811ee
Revises: 
Create Date: 2026-03-23 08:04:22.020173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = 'a857605811ee'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('source_reference', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('document_type', sa.String(length=100), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='archive_data'
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username'),
    schema='archive_data'
    )
    op.create_table('aircraft_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('designation', sa.String(length=100), nullable=False),
    sa.Column('manufacturer', sa.String(length=255), nullable=True),
    sa.Column('common_name', sa.String(length=255), nullable=True),
    sa.Column('variants', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('trust_level', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='archive_knowledge'
    )
    op.create_table('document_schemas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('column_definitions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('example_collection_id', sa.UUID(), nullable=True),
    sa.Column('trust_level', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_type'),
    schema='archive_knowledge'
    )
    op.create_table('unit_designations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('abbreviation', sa.String(length=100), nullable=False),
    sa.Column('full_name', sa.String(length=500), nullable=True),
    sa.Column('unit_type', sa.String(length=100), nullable=True),
    sa.Column('parent_unit_id', sa.UUID(), nullable=True),
    sa.Column('active_from', sa.Date(), nullable=True),
    sa.Column('active_to', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('trust_level', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['parent_unit_id'], ['archive_knowledge.unit_designations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='archive_knowledge'
    )
    op.create_table('pages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('collection_id', sa.UUID(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(length=1000), nullable=True),
    sa.Column('ocr_status', sa.String(length=50), nullable=False),
    sa.Column('ocr_confidence', sa.Float(), nullable=True),
    sa.Column('raw_ocr_text', sa.Text(), nullable=True),
    sa.Column('segmentation_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['archive_data.collections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='archive_data'
    )
    op.create_table('pipeline_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('collection_id', sa.UUID(), nullable=False),
    sa.Column('stage', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('total_pages', sa.Integer(), nullable=True),
    sa.Column('processed_pages', sa.Integer(), nullable=False),
    sa.Column('last_processed_page_id', sa.UUID(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['archive_data.collections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='archive_data'
    )
    op.create_table('glossary',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('term', sa.String(length=500), nullable=False),
    sa.Column('definition', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('trust_level', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=500), nullable=True),
    sa.Column('proposed_by', sa.UUID(), nullable=True),
    sa.Column('verified_by', sa.UUID(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.ForeignKeyConstraint(['proposed_by'], ['archive_data.users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['verified_by'], ['archive_data.users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='archive_knowledge'
    )
    op.create_table('knowledge_reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('old_trust_level', sa.String(length=50), nullable=True),
    sa.Column('new_trust_level', sa.String(length=50), nullable=True),
    sa.Column('reviewer', sa.UUID(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reviewer'], ['archive_data.users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='archive_knowledge'
    )
    op.create_table('records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('page_id', sa.UUID(), nullable=False),
    sa.Column('page_id_end', sa.UUID(), nullable=True),
    sa.Column('entry_number', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('unit_designation', sa.String(length=255), nullable=True),
    sa.Column('aircraft_type', sa.String(length=255), nullable=True),
    sa.Column('werknummer', sa.String(length=100), nullable=True),
    sa.Column('incident_type', sa.String(length=100), nullable=True),
    sa.Column('incident_description', sa.Text(), nullable=True),
    sa.Column('damage_percentage', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=500), nullable=True),
    sa.Column('raw_text_original', sa.Text(), nullable=True),
    sa.Column('bounding_boxes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('search_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['archive_data.pages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['page_id_end'], ['archive_data.pages.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='archive_data'
    )
    op.create_table('personnel',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('record_id', sa.UUID(), nullable=False),
    sa.Column('rank_abbreviation', sa.String(length=50), nullable=True),
    sa.Column('rank_full', sa.String(length=255), nullable=True),
    sa.Column('surname', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('fate', sa.String(length=255), nullable=True),
    sa.Column('fate_english', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['record_id'], ['archive_data.records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='archive_data'
    )
    op.create_table('record_corrections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('record_id', sa.UUID(), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('original_value', sa.Text(), nullable=True),
    sa.Column('corrected_value', sa.Text(), nullable=True),
    sa.Column('corrected_by', sa.UUID(), nullable=True),
    sa.Column('corrected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['corrected_by'], ['archive_data.users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['record_id'], ['archive_data.records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='archive_data'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('record_corrections', schema='archive_data')
    op.drop_table('personnel', schema='archive_data')
    op.drop_table('records', schema='archive_data')
    op.drop_table('knowledge_reviews', schema='archive_knowledge')
    op.drop_table('glossary', schema='archive_knowledge')
    op.drop_table('pipeline_jobs', schema='archive_data')
    op.drop_table('pages', schema='archive_data')
    op.drop_table('unit_designations', schema='archive_knowledge')
    op.drop_table('document_schemas', schema='archive_knowledge')
    op.drop_table('aircraft_types', schema='archive_knowledge')
    op.drop_table('users', schema='archive_data')
    op.drop_table('collections', schema='archive_data')
    # ### end Alembic commands ###
